package org.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public ArticleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andArticleIdIsNull() {
			addCriterion("article_id is null");
			return (Criteria) this;
		}

		public Criteria andArticleIdIsNotNull() {
			addCriterion("article_id is not null");
			return (Criteria) this;
		}

		public Criteria andArticleIdEqualTo(String value) {
			addCriterion("article_id =", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotEqualTo(String value) {
			addCriterion("article_id <>", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdGreaterThan(String value) {
			addCriterion("article_id >", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdGreaterThanOrEqualTo(String value) {
			addCriterion("article_id >=", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLessThan(String value) {
			addCriterion("article_id <", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLessThanOrEqualTo(String value) {
			addCriterion("article_id <=", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLike(String value) {
			addCriterion("article_id like", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotLike(String value) {
			addCriterion("article_id not like", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdIn(List<String> values) {
			addCriterion("article_id in", values, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotIn(List<String> values) {
			addCriterion("article_id not in", values, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdBetween(String value1, String value2) {
			addCriterion("article_id between", value1, value2, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotBetween(String value1, String value2) {
			addCriterion("article_id not between", value1, value2, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleNameIsNull() {
			addCriterion("article_name is null");
			return (Criteria) this;
		}

		public Criteria andArticleNameIsNotNull() {
			addCriterion("article_name is not null");
			return (Criteria) this;
		}

		public Criteria andArticleNameEqualTo(String value) {
			addCriterion("article_name =", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameNotEqualTo(String value) {
			addCriterion("article_name <>", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameGreaterThan(String value) {
			addCriterion("article_name >", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameGreaterThanOrEqualTo(String value) {
			addCriterion("article_name >=", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameLessThan(String value) {
			addCriterion("article_name <", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameLessThanOrEqualTo(String value) {
			addCriterion("article_name <=", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameLike(String value) {
			addCriterion("article_name like", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameNotLike(String value) {
			addCriterion("article_name not like", value, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameIn(List<String> values) {
			addCriterion("article_name in", values, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameNotIn(List<String> values) {
			addCriterion("article_name not in", values, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameBetween(String value1, String value2) {
			addCriterion("article_name between", value1, value2, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleNameNotBetween(String value1, String value2) {
			addCriterion("article_name not between", value1, value2, "articleName");
			return (Criteria) this;
		}

		public Criteria andArticleTimeIsNull() {
			addCriterion("article_time is null");
			return (Criteria) this;
		}

		public Criteria andArticleTimeIsNotNull() {
			addCriterion("article_time is not null");
			return (Criteria) this;
		}

		public Criteria andArticleTimeEqualTo(String value) {
			addCriterion("article_time =", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeNotEqualTo(String value) {
			addCriterion("article_time <>", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeGreaterThan(String value) {
			addCriterion("article_time >", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeGreaterThanOrEqualTo(String value) {
			addCriterion("article_time >=", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeLessThan(String value) {
			addCriterion("article_time <", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeLessThanOrEqualTo(String value) {
			addCriterion("article_time <=", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeLike(String value) {
			addCriterion("article_time like", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeNotLike(String value) {
			addCriterion("article_time not like", value, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeIn(List<String> values) {
			addCriterion("article_time in", values, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeNotIn(List<String> values) {
			addCriterion("article_time not in", values, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeBetween(String value1, String value2) {
			addCriterion("article_time between", value1, value2, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleTimeNotBetween(String value1, String value2) {
			addCriterion("article_time not between", value1, value2, "articleTime");
			return (Criteria) this;
		}

		public Criteria andArticleIpIsNull() {
			addCriterion("article_ip is null");
			return (Criteria) this;
		}

		public Criteria andArticleIpIsNotNull() {
			addCriterion("article_ip is not null");
			return (Criteria) this;
		}

		public Criteria andArticleIpEqualTo(String value) {
			addCriterion("article_ip =", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpNotEqualTo(String value) {
			addCriterion("article_ip <>", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpGreaterThan(String value) {
			addCriterion("article_ip >", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpGreaterThanOrEqualTo(String value) {
			addCriterion("article_ip >=", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpLessThan(String value) {
			addCriterion("article_ip <", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpLessThanOrEqualTo(String value) {
			addCriterion("article_ip <=", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpLike(String value) {
			addCriterion("article_ip like", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpNotLike(String value) {
			addCriterion("article_ip not like", value, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpIn(List<String> values) {
			addCriterion("article_ip in", values, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpNotIn(List<String> values) {
			addCriterion("article_ip not in", values, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpBetween(String value1, String value2) {
			addCriterion("article_ip between", value1, value2, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleIpNotBetween(String value1, String value2) {
			addCriterion("article_ip not between", value1, value2, "articleIp");
			return (Criteria) this;
		}

		public Criteria andArticleClickIsNull() {
			addCriterion("article_click is null");
			return (Criteria) this;
		}

		public Criteria andArticleClickIsNotNull() {
			addCriterion("article_click is not null");
			return (Criteria) this;
		}

		public Criteria andArticleClickEqualTo(Integer value) {
			addCriterion("article_click =", value, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickNotEqualTo(Integer value) {
			addCriterion("article_click <>", value, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickGreaterThan(Integer value) {
			addCriterion("article_click >", value, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickGreaterThanOrEqualTo(Integer value) {
			addCriterion("article_click >=", value, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickLessThan(Integer value) {
			addCriterion("article_click <", value, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickLessThanOrEqualTo(Integer value) {
			addCriterion("article_click <=", value, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickIn(List<Integer> values) {
			addCriterion("article_click in", values, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickNotIn(List<Integer> values) {
			addCriterion("article_click not in", values, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickBetween(Integer value1, Integer value2) {
			addCriterion("article_click between", value1, value2, "articleClick");
			return (Criteria) this;
		}

		public Criteria andArticleClickNotBetween(Integer value1, Integer value2) {
			addCriterion("article_click not between", value1, value2, "articleClick");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdIsNull() {
			addCriterion("sort_article_id is null");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdIsNotNull() {
			addCriterion("sort_article_id is not null");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdEqualTo(String value) {
			addCriterion("sort_article_id =", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdNotEqualTo(String value) {
			addCriterion("sort_article_id <>", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdGreaterThan(String value) {
			addCriterion("sort_article_id >", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdGreaterThanOrEqualTo(String value) {
			addCriterion("sort_article_id >=", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdLessThan(String value) {
			addCriterion("sort_article_id <", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdLessThanOrEqualTo(String value) {
			addCriterion("sort_article_id <=", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdLike(String value) {
			addCriterion("sort_article_id like", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdNotLike(String value) {
			addCriterion("sort_article_id not like", value, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdIn(List<String> values) {
			addCriterion("sort_article_id in", values, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdNotIn(List<String> values) {
			addCriterion("sort_article_id not in", values, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdBetween(String value1, String value2) {
			addCriterion("sort_article_id between", value1, value2, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andSortArticleIdNotBetween(String value1, String value2) {
			addCriterion("sort_article_id not between", value1, value2, "sortArticleId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("type_id is null");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("type_id is not null");
			return (Criteria) this;
		}

		public Criteria andTypeIdEqualTo(String value) {
			addCriterion("type_id =", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotEqualTo(String value) {
			addCriterion("type_id <>", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThan(String value) {
			addCriterion("type_id >", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("type_id >=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThan(String value) {
			addCriterion("type_id <", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(String value) {
			addCriterion("type_id <=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLike(String value) {
			addCriterion("type_id like", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotLike(String value) {
			addCriterion("type_id not like", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIn(List<String> values) {
			addCriterion("type_id in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotIn(List<String> values) {
			addCriterion("type_id not in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdBetween(String value1, String value2) {
			addCriterion("type_id between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotBetween(String value1, String value2) {
			addCriterion("type_id not between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIsNull() {
			addCriterion("article_type is null");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIsNotNull() {
			addCriterion("article_type is not null");
			return (Criteria) this;
		}

		public Criteria andArticleTypeEqualTo(String value) {
			addCriterion("article_type =", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotEqualTo(String value) {
			addCriterion("article_type <>", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeGreaterThan(String value) {
			addCriterion("article_type >", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeGreaterThanOrEqualTo(String value) {
			addCriterion("article_type >=", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLessThan(String value) {
			addCriterion("article_type <", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLessThanOrEqualTo(String value) {
			addCriterion("article_type <=", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLike(String value) {
			addCriterion("article_type like", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotLike(String value) {
			addCriterion("article_type not like", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIn(List<String> values) {
			addCriterion("article_type in", values, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotIn(List<String> values) {
			addCriterion("article_type not in", values, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeBetween(String value1, String value2) {
			addCriterion("article_type between", value1, value2, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotBetween(String value1, String value2) {
			addCriterion("article_type not between", value1, value2, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleUpIsNull() {
			addCriterion("article_up is null");
			return (Criteria) this;
		}

		public Criteria andArticleUpIsNotNull() {
			addCriterion("article_up is not null");
			return (Criteria) this;
		}

		public Criteria andArticleUpEqualTo(String value) {
			addCriterion("article_up =", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpNotEqualTo(String value) {
			addCriterion("article_up <>", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpGreaterThan(String value) {
			addCriterion("article_up >", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpGreaterThanOrEqualTo(String value) {
			addCriterion("article_up >=", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpLessThan(String value) {
			addCriterion("article_up <", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpLessThanOrEqualTo(String value) {
			addCriterion("article_up <=", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpLike(String value) {
			addCriterion("article_up like", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpNotLike(String value) {
			addCriterion("article_up not like", value, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpIn(List<String> values) {
			addCriterion("article_up in", values, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpNotIn(List<String> values) {
			addCriterion("article_up not in", values, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpBetween(String value1, String value2) {
			addCriterion("article_up between", value1, value2, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleUpNotBetween(String value1, String value2) {
			addCriterion("article_up not between", value1, value2, "articleUp");
			return (Criteria) this;
		}

		public Criteria andArticleSupportIsNull() {
			addCriterion("article_support is null");
			return (Criteria) this;
		}

		public Criteria andArticleSupportIsNotNull() {
			addCriterion("article_support is not null");
			return (Criteria) this;
		}

		public Criteria andArticleSupportEqualTo(String value) {
			addCriterion("article_support =", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportNotEqualTo(String value) {
			addCriterion("article_support <>", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportGreaterThan(String value) {
			addCriterion("article_support >", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportGreaterThanOrEqualTo(String value) {
			addCriterion("article_support >=", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportLessThan(String value) {
			addCriterion("article_support <", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportLessThanOrEqualTo(String value) {
			addCriterion("article_support <=", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportLike(String value) {
			addCriterion("article_support like", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportNotLike(String value) {
			addCriterion("article_support not like", value, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportIn(List<String> values) {
			addCriterion("article_support in", values, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportNotIn(List<String> values) {
			addCriterion("article_support not in", values, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportBetween(String value1, String value2) {
			addCriterion("article_support between", value1, value2, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSupportNotBetween(String value1, String value2) {
			addCriterion("article_support not between", value1, value2, "articleSupport");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryIsNull() {
			addCriterion("article_summary is null");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryIsNotNull() {
			addCriterion("article_summary is not null");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryEqualTo(String value) {
			addCriterion("article_summary =", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryNotEqualTo(String value) {
			addCriterion("article_summary <>", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryGreaterThan(String value) {
			addCriterion("article_summary >", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryGreaterThanOrEqualTo(String value) {
			addCriterion("article_summary >=", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryLessThan(String value) {
			addCriterion("article_summary <", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryLessThanOrEqualTo(String value) {
			addCriterion("article_summary <=", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryLike(String value) {
			addCriterion("article_summary like", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryNotLike(String value) {
			addCriterion("article_summary not like", value, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryIn(List<String> values) {
			addCriterion("article_summary in", values, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryNotIn(List<String> values) {
			addCriterion("article_summary not in", values, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryBetween(String value1, String value2) {
			addCriterion("article_summary between", value1, value2, "articleSummary");
			return (Criteria) this;
		}

		public Criteria andArticleSummaryNotBetween(String value1, String value2) {
			addCriterion("article_summary not between", value1, value2, "articleSummary");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbg.generated  Mon Oct 14 10:02:31 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 02 15:56:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}