package com.myBlog.entity.article;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_name
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_time
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_ip
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_click
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private Integer articleClick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.sort_article_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String sortArticleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.user_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.type_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_type
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_up
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleUp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_support
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleSupport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_content
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	private String articleContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_id
	 * @return  the value of article.article_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_id
	 * @param articleId  the value for article.article_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleId(String articleId) {
		this.articleId = articleId == null ? null : articleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_name
	 * @return  the value of article.article_name
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleName() {
		return articleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_name
	 * @param articleName  the value for article.article_name
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleName(String articleName) {
		this.articleName = articleName == null ? null : articleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_time
	 * @return  the value of article.article_time
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleTime() {
		return articleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_time
	 * @param articleTime  the value for article.article_time
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleTime(String articleTime) {
		this.articleTime = articleTime == null ? null : articleTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_ip
	 * @return  the value of article.article_ip
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleIp() {
		return articleIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_ip
	 * @param articleIp  the value for article.article_ip
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleIp(String articleIp) {
		this.articleIp = articleIp == null ? null : articleIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_click
	 * @return  the value of article.article_click
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public Integer getArticleClick() {
		return articleClick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_click
	 * @param articleClick  the value for article.article_click
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleClick(Integer articleClick) {
		this.articleClick = articleClick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.sort_article_id
	 * @return  the value of article.sort_article_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getSortArticleId() {
		return sortArticleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.sort_article_id
	 * @param sortArticleId  the value for article.sort_article_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setSortArticleId(String sortArticleId) {
		this.sortArticleId = sortArticleId == null ? null : sortArticleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.user_id
	 * @return  the value of article.user_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.user_id
	 * @param userId  the value for article.user_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.type_id
	 * @return  the value of article.type_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.type_id
	 * @param typeId  the value for article.type_id
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId == null ? null : typeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_type
	 * @return  the value of article.article_type
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleType() {
		return articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_type
	 * @param articleType  the value for article.article_type
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleType(String articleType) {
		this.articleType = articleType == null ? null : articleType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_up
	 * @return  the value of article.article_up
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleUp() {
		return articleUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_up
	 * @param articleUp  the value for article.article_up
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleUp(String articleUp) {
		this.articleUp = articleUp == null ? null : articleUp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_support
	 * @return  the value of article.article_support
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleSupport() {
		return articleSupport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_support
	 * @param articleSupport  the value for article.article_support
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleSupport(String articleSupport) {
		this.articleSupport = articleSupport == null ? null : articleSupport.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_content
	 * @return  the value of article.article_content
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public String getArticleContent() {
		return articleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_content
	 * @param articleContent  the value for article.article_content
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent == null ? null : articleContent.trim();
	}
}