package com.myBlog.entity.article;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_name
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private String articleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_time
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Date articleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_ip
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private String articleIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_click
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Integer articleClick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sort_article_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Integer sortArticleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Byte typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_type
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Integer articleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_up
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Byte articleUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_support
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private Byte articleSupport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_name
     *
     * @return the value of article.article_name
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_name
     *
     * @param articleName the value for article.article_name
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_time
     *
     * @return the value of article.article_time
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Date getArticleTime() {
        return articleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_time
     *
     * @param articleTime the value for article.article_time
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleTime(Date articleTime) {
        this.articleTime = articleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_ip
     *
     * @return the value of article.article_ip
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public String getArticleIp() {
        return articleIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_ip
     *
     * @param articleIp the value for article.article_ip
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleIp(String articleIp) {
        this.articleIp = articleIp == null ? null : articleIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_click
     *
     * @return the value of article.article_click
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Integer getArticleClick() {
        return articleClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_click
     *
     * @param articleClick the value for article.article_click
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleClick(Integer articleClick) {
        this.articleClick = articleClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sort_article_id
     *
     * @return the value of article.sort_article_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Integer getSortArticleId() {
        return sortArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sort_article_id
     *
     * @param sortArticleId the value for article.sort_article_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setSortArticleId(Integer sortArticleId) {
        this.sortArticleId = sortArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_id
     *
     * @return the value of article.user_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_id
     *
     * @param userId the value for article.user_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type_id
     *
     * @return the value of article.type_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Byte getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type_id
     *
     * @param typeId the value for article.type_id
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setTypeId(Byte typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_type
     *
     * @return the value of article.article_type
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Integer getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_type
     *
     * @param articleType the value for article.article_type
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_up
     *
     * @return the value of article.article_up
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Byte getArticleUp() {
        return articleUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_up
     *
     * @param articleUp the value for article.article_up
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleUp(Byte articleUp) {
        this.articleUp = articleUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_support
     *
     * @return the value of article.article_support
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public Byte getArticleSupport() {
        return articleSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_support
     *
     * @param articleSupport the value for article.article_support
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleSupport(Byte articleSupport) {
        this.articleSupport = articleSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbg.generated Mon Sep 02 15:56:30 CST 2019
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }
}