package com.myBlog.service.article;

import java.util.List;

import com.myBlog.entity.article.Article;
import com.myBlog.entity.article.ArticleExample;

public interface ArticleService {
	/**
	 * 新增博客文章；
	 * @param 
	 * @return
	 */
	public int addArticle(Article article);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	int deleteByPrimaryKey(String articleId);

	/**
	 * 查询所有的博客
	 * @return
	 */
	List<Article> queryBlogs(Article record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	List<Article> selectByExampleWithBLOBs(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	List<Article> selectByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	Article selectByPrimaryKey(String articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Sep 25 16:06:57 CST 2019
	 */
	int updateByPrimaryKey(Article record);

}
